name: Build the container image

on:
  workflow_dispatch:
    inputs:
      caddy_version:
        description: 'Caddy版本 (如 2.10.0)'
        required: true
      module_version:
        description: 'cloudflare模块版本 (如 0.2.1)'
        required: true
  release:
    types: [published]

jobs:
  build:
    name: Build the container image
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    strategy:
      matrix:
        arch: [amd64, arm64]
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub container registry
        uses: docker/login-action@v3
        with:
          password: ${{ github.token }}
          registry: ghcr.io
          username: ${{ github.actor }}

      - name: Build and push
        id: build
        uses: docker/build-push-action@v4
        with:
          context: .
          platforms: ${{ matrix.platform }}
          push: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            CADDY_VERSION=${{ github.event.inputs.caddy_version }}
            MODULE_VERSION=${{ github.event.inputs.module_version }}
          labels: |
            org.opencontainers.image.source=https://github.com/baowei/caddy-cloudflare
          tags: ghcr.io/baowei/caddy-cloudflare:${{ github.event.inputs.caddy_version }}
          outputs: type=local,dest=./build/${{ matrix.arch }}

      - name: Package binary
        run: |
          mkdir -p artifacts
          cd build/${{ matrix.arch }}
          tar czvf ../../artifacts/caddy_${{ github.event.inputs.caddy_version }}_linux_${{ matrix.arch }}.tar.gz \
            --transform 'flags=r;s|usr/bin/||' usr/bin/caddy
          cd ../..
          (cd artifacts && sha256sum caddy_${{ github.event.inputs.caddy_version }}_linux_${{ matrix.arch }}.tar.gz) \
           >> artifacts/caddy_${{ github.event.inputs.caddy_version }}_${{ matrix.arch }}_checksums.txt

      - name: Create Release and Upload Assets
        uses: softprops/action-gh-release@v2
        with:
          name: Caddy ${{ github.event.inputs.caddy_version }}
          tag_name: v${{ github.event.inputs.caddy_version }}
          files: |
            artifacts/caddy_${{ github.event.inputs.caddy_version }}_linux_*.tar.gz
            artifacts/caddy_*_checksums.txt
          draft: false
          prerelease: false
